name: Email Reminder

on:
  schedule:
    # Chạy vào 10:15 UTC hàng ngày (điều chỉnh múi giờ phù hợp)
    - cron: '15 10 * * *'
  workflow_dispatch:  # Cho phép chạy thủ công khi cần

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yagmail keyring
          
      - name: Run reminder script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER: ${{ secrets.RECEIVER_EMAIL }}
        run: python reminder.py
